### PR TITLE
Improvements related to android Dependencies

### PR DESCRIPTION
**Pull request by juanpedromoreno**
This PR improves the sbt dependencies management with android project libs.

Please, @javipacheco @fedefernandez could you take a look and check if it is would be useful for you? Thanks!

### CODE REVIEW

**Comment by javipacheco** [comment]
Why don't have the branch `activator` file? When I use my local activator app the activator website is opened

**Comment by juanpedromoreno** [comment]
That's odd. Lastly I'm using sbt directly. Anyway you could copy the last activator version downloaded from the typesafe website and try again. 

Let me know that if it worked for you.

**Comment by fedefernandez** [comment]
@juanpedromoreno this configuration is for a "two modules" configuration, isn't it? it requires a lot of changes in order to support three/four modules for example?

**Comment by juanpedromoreno** [comment]
@fedefernandez I do not think so. You could edit this build file in order to increase the number of modules of your project. 

https://github.com/juanpedromoreno/scala-android-multimodule/blob/master/project/AppBuild.scala#L7

Obviously, it depends the characteristics of those projects if the configuration became more difficult or not.

Anyway, Android over SBT with multi-modules doesn't give us much more alternatives.

**Comment by fedefernandez** [comment]
LGTM! good work!

**Pull request merged**
